name: 02 Conditional Steps

on:
  workflow_dispatch: # This event triggers the workflow manually

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Exit Code 0
        id: sucessfull_step
        run: |
          echo "exit code 0"
          exit 0  # Success (exit code 0)
        shell: bash # If you want you can change the shell per step

      - name: Step 2 - Execute if previous step succeeded
        if: ${{success()}} # Only run this step if the previous step succeeded
        run: |
          echo "running because the previous step has succeeded"

      - name: Step 3 - I am Failing
        run: |
          echo "i am failing"
          exit 1 # Failure (non-zero exit code)

      - name: Step 4 - i will never execute
        run: |
          echo "i will never execute"

      - name: Step 5 - Execute on Workflow Failure
        if: ${{failure()}} # Only run this step if the workflow failed(to clean up the environment )
        run: |
          echo "Workflow Failed"
