name: 06 Passing Data Between Steps

on:
  workflow_dispatch:

jobs:
  data-passing:
    runs-on: ubuntu-latest
    steps:
      - name: Create data
        id: sender
        # this step will set the output name for this step to Michal
        run: |
          echo "name=Michael" >> $GITHUB_OUTPUT

      - name: Receive data
        run: |
          echo ${{steps.sender.output.name}}
